[package]
name = "desired_state"
version = "0.1.0"
edition = "2024"

[dependencies]
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
notify = "6"
log = "0.4"
env_logger = "0.11"
